version: '3.9'
services:
  postandcomments:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started


  db:
    image: postgres
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
