version: '3.9'
services:
  postandcommentstests:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres
    restart: always
    volumes:
       - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5436
volumes:
  pgdata:

