// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postId"`
	Body     string     `json:"body"`
	ParentID *string    `json:"parentId,omitempty"`
	Children []*Comment `json:"children"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Body          string     `json:"body"`
	Comments      []*Comment `json:"comments"`
	AllowComments bool       `json:"allowComments"`
}

type Query struct {
}

type Subscription struct {
}
